USE adlister_db;

insert into dogs (age, name, reside_state) values (4, 'Focused', 'CA');
insert into dogs (age, name, reside_state) values (61, 'foreground', 'RU');
insert into dogs (age, name, reside_state) values (46, 'multi-state', 'US');
insert into dogs (age, name, reside_state) values (64, 'Universal', 'FR');
insert into dogs (age, name, reside_state) values (75, 'Optimized', 'CZ');
insert into dogs (age, name, reside_state) values (45, 'regional', 'CN');
insert into dogs (age, name, reside_state) values (39, 'logistical', 'SE');
insert into dogs (age, name, reside_state) values (72, 'dedicated', 'PT');
insert into dogs (age, name, reside_state) values (97, 'Focused', 'CN');
insert into dogs (age, name, reside_state) values (27, 'Automated', 'ID');
insert into dogs (age, name, reside_state) values (78, '6th generation', 'UA');
insert into dogs (age, name, reside_state) values (88, 'Multi-tiered', 'CN');
insert into dogs (age, name, reside_state) values (3, 'user-facing', 'ID');
insert into dogs (age, name, reside_state) values (26, 'Switchable', 'CO');
insert into dogs (age, name, reside_state) values (60, 'emulation', 'RU');
insert into dogs (age, name, reside_state) values (79, 'Public-key', 'AR');
insert into dogs (age, name, reside_state) values (60, 'implementation', 'RU');
insert into dogs (age, name, reside_state) values (35, 'standardization', 'CA');
insert into dogs (age, name, reside_state) values (81, 'throughput', 'CN');
insert into dogs (age, name, reside_state) values (56, 'knowledge base', 'FR');
insert into dogs (age, name, reside_state) values (38, 'system-worthy', 'SI');
insert into dogs (age, name, reside_state) values (88, 'hierarchy', 'CA');
insert into dogs (age, name, reside_state) values (33, 'support', 'CN');
insert into dogs (age, name, reside_state) values (67, 'Public-key', 'AF');
insert into dogs (age, name, reside_state) values (52, 'tangible', 'RU');
insert into dogs (age, name, reside_state) values (75, 'groupware', 'PH');
insert into dogs (age, name, reside_state) values (65, 'grid-enabled', 'ML');
insert into dogs (age, name, reside_state) values (98, 'systemic', 'PL');
insert into dogs (age, name, reside_state) values (26, 'Graphical User Interface', 'VE');
insert into dogs (age, name, reside_state) values (8, 'asynchronous', 'NI');
insert into dogs (age, name, reside_state) values (31, 'matrices', 'IR');
insert into dogs (age, name, reside_state) values (20, 'even-keeled', 'ID');
insert into dogs (age, name, reside_state) values (41, 'needs-based', 'CN');
insert into dogs (age, name, reside_state) values (82, 'analyzing', 'RU');
insert into dogs (age, name, reside_state) values (56, 'access', 'FR');
insert into dogs (age, name, reside_state) values (32, 'moratorium', 'FR');
insert into dogs (age, name, reside_state) values (55, 'Innovative', 'MU');
insert into dogs (age, name, reside_state) values (19, 'matrix', 'LU');
insert into dogs (age, name, reside_state) values (3, 'application', 'BR');
insert into dogs (age, name, reside_state) values (19, 'Inverse', 'MX');
insert into dogs (age, name, reside_state) values (29, 'Triple-buffered', 'CN');
insert into dogs (age, name, reside_state) values (57, 'local area network', 'FR');
insert into dogs (age, name, reside_state) values (21, 'Customer-focused', 'MY');
insert into dogs (age, name, reside_state) values (25, 'fault-tolerant', 'CN');
insert into dogs (age, name, reside_state) values (43, 'optimal', 'CZ');
insert into dogs (age, name, reside_state) values (10, 'Graphic Interface', 'CN');
insert into dogs (age, name, reside_state) values (26, 'uniform', 'CN');
insert into dogs (age, name, reside_state) values (49, 'high-level', 'AR');
insert into dogs (age, name, reside_state) values (26, 'Seamless', 'CN');
insert into dogs (age, name, reside_state) values (51, 'Vision-oriented', 'UA');
