USE springblog_db;

insert into posts (title, body, username_id) values ('velit vivamus vel nulla', 'Open biopsy of rectum', 1);
insert into posts (title, body, username_id) values ('volutpat in congue etiam justo', 'Suture of laceration of diaphragm', 1);
insert into posts (title, body, username_id) values ('ante nulla justo', 'Other x-ray of thoracic spine', 1);
insert into posts (title, body, username_id) values ('a suscipit', 'Fitting of prosthesis below knee', 1);
insert into posts (title, body, username_id) values ('sollicitudin mi sit amet', 'Insertion of temporary transvenous pacemaker system', 1);
insert into posts (title, body, username_id) values ('vestibulum sed magna', 'Replacement of ureterostomy tube', 1);
insert into posts (title, body, username_id) values ('nulla ut erat', 'Repair of retinal detachment with laser photocoagulation', 1);
insert into posts (title, body, username_id) values ('posuere nonummy integer', 'Closed [endoscopic] biopsy of bronchus', 1);
insert into posts (title, body, username_id) values ('iaculis diam', 'Laparoscopic bilateral repair of inguinal hernia with graft or prosthesis, not otherwise specified', 1);
insert into posts (title, body, username_id) values ('sed vel enim sit amet', 'Biopsy of external ear', 1);
insert into posts (title, body, username_id) values ('non mauris morbi non', 'Insertion of catheter into spinal canal for infusion of therapeutic or palliative substances', 1);
insert into posts (title, body, username_id) values ('interdum venenatis turpis enim', 'Esophageal manometry', 1);
insert into posts (title, body, username_id) values ('vivamus vel nulla eget', 'Other adjustment of lid position', 1);
insert into posts (title, body, username_id) values ('nulla tempus', 'Suture of laceration of anus', 1);
insert into posts (title, body, username_id) values ('mi sit amet lobortis sapien', 'Other intrathoracic vascular shunt or bypass', 1);
insert into posts (title, body, username_id) values ('fusce posuere', 'Hyperbaric oxygenation', 1);
insert into posts (title, body, username_id) values ('sapien placerat ante', 'Other lamellar keratoplasty', 1);
insert into posts (title, body, username_id) values ('montes nascetur ridiculus', 'Excision of lesion of lacrimal gland', 1);
insert into posts (title, body, username_id) values ('ipsum dolor', 'Revision of knee replacement, tibial component', 1);
insert into posts (title, body, username_id) values ('molestie lorem', 'Transplantation of ovary', 1);
insert into posts (title, body, username_id) values ('ante vestibulum ante', 'Microscopic examination of specimen from trachea, bronchus, pleura, lung, and other thoracic specimen, and of sputum, culture and sensitivity', 1);
insert into posts (title, body, username_id) values ('pretium iaculis diam erat fermentum', 'Control of epistaxis by (transantral) ligation of the maxillary artery', 1);
insert into posts (title, body, username_id) values ('quam sapien varius ut blandit', 'Full-mouth x-ray of teeth', 1);
insert into posts (title, body, username_id) values ('eros viverra eget congue', 'Replacement and refitting of vaginal diaphragm', 1);
insert into posts (title, body, username_id) values ('congue etiam justo etiam', 'Implantation or insertion of biventricular external heart assist system', 1);
insert into posts (title, body, username_id) values ('at velit eu est congue', 'Endoscopic retrograde cholangiography [ERC]', 1);
insert into posts (title, body, username_id) values ('mauris sit', 'Unilateral injection into breast for augmentation', 1);
insert into posts (title, body, username_id) values ('ipsum ac tellus', 'Pharyngeal diverticulectomy', 1);
insert into posts (title, body, username_id) values ('magna ac consequat', 'Other excision of vessels, unspecified site', 1);
insert into posts (title, body, username_id) values ('elementum pellentesque', 'Arteriography of renal arteries', 1);
insert into posts (title, body, username_id) values ('justo sit amet sapien', 'Wedge resection of ovary', 1);
insert into posts (title, body, username_id) values ('eu orci mauris lacinia', 'Excision of nipple', 1);
insert into posts (title, body, username_id) values ('sapien in sapien iaculis', 'Laparoscopic repair of indirect inguinal hernia with graft or prosthesis', 1);
insert into posts (title, body, username_id) values ('augue aliquam erat', 'Other operations on anus', 1);
insert into posts (title, body, username_id) values ('nisl ut volutpat sapien', 'Dispensing of other low vision aids', 1);
insert into posts (title, body, username_id) values ('ligula vehicula consequat', 'Other glossotomy', 1);
insert into posts (title, body, username_id) values ('magnis dis', 'Refusion of lumbar and lumbosacral spine, anterior column, anterior technique', 1);
insert into posts (title, body, username_id) values ('luctus ultricies', 'Incision of gum or alveolar bone', 1);
insert into posts (title, body, username_id) values ('ultrices posuere cubilia', 'Injection or infusion of biological response modifier [BRM] as an antineoplastic agent', 1);
insert into posts (title, body, username_id) values ('vel accumsan tellus nisi', 'Hypothermia (central) (local)', 1);
insert into posts (title, body, username_id) values ('interdum venenatis turpis enim blandit', 'Implantation or replacement of automatic cardioverter/defibrillator, total system [AICD]', 1);
insert into posts (title, body, username_id) values ('nunc commodo placerat praesent blandit', 'Tendon graft', 1);
insert into posts (title, body, username_id) values ('nibh in hac habitasse platea', 'Closure of fistula of mouth', 1);
insert into posts (title, body, username_id) values ('morbi vestibulum velit', 'Tendon pulley reconstruction other than hand', 1);
insert into posts (title, body, username_id) values ('amet erat nulla tempus vivamus', 'Other tenodesis of hand', 1);
insert into posts (title, body, username_id) values ('maecenas pulvinar', 'Open reduction of maxillary fracture', 1);
insert into posts (title, body, username_id) values ('vulputate luctus cum sociis', 'Implantation or replacement of carotid sinus stimulation lead(s) only', 1);
insert into posts (title, body, username_id) values ('volutpat dui maecenas tristique', 'Other repair of knee', 1);
insert into posts (title, body, username_id) values ('dolor sit amet', 'Internal fixation of bone without fracture reduction, carpals and metacarpals', 1);
insert into posts (title, body, username_id) values ('id justo', 'Total excision of pineal gland', 1);
insert into users (email, password, username) values ('user.email.com', 'userpassword', 'user')