USE springblog_db;

insert into posts (title, body) values ('velit vivamus vel nulla', 'Open biopsy of rectum');
insert into posts (title, body) values ('volutpat in congue etiam justo', 'Suture of laceration of diaphragm');
insert into posts (title, body) values ('ante nulla justo', 'Other x-ray of thoracic spine');
insert into posts (title, body) values ('a suscipit', 'Fitting of prosthesis below knee');
insert into posts (title, body) values ('sollicitudin mi sit amet', 'Insertion of temporary transvenous pacemaker system');
insert into posts (title, body) values ('vestibulum sed magna', 'Replacement of ureterostomy tube');
insert into posts (title, body) values ('nulla ut erat', 'Repair of retinal detachment with laser photocoagulation');
insert into posts (title, body) values ('posuere nonummy integer', 'Closed [endoscopic] biopsy of bronchus');
insert into posts (title, body) values ('iaculis diam', 'Laparoscopic bilateral repair of inguinal hernia with graft or prosthesis, not otherwise specified');
insert into posts (title, body) values ('sed vel enim sit amet', 'Biopsy of external ear');
insert into posts (title, body) values ('non mauris morbi non', 'Insertion of catheter into spinal canal for infusion of therapeutic or palliative substances');
insert into posts (title, body) values ('interdum venenatis turpis enim', 'Esophageal manometry');
insert into posts (title, body) values ('vivamus vel nulla eget', 'Other adjustment of lid position');
insert into posts (title, body) values ('nulla tempus', 'Suture of laceration of anus');
insert into posts (title, body) values ('mi sit amet lobortis sapien', 'Other intrathoracic vascular shunt or bypass');
insert into posts (title, body) values ('fusce posuere', 'Hyperbaric oxygenation');
insert into posts (title, body) values ('sapien placerat ante', 'Other lamellar keratoplasty');
insert into posts (title, body) values ('montes nascetur ridiculus', 'Excision of lesion of lacrimal gland');
insert into posts (title, body) values ('ipsum dolor', 'Revision of knee replacement, tibial component');
insert into posts (title, body) values ('molestie lorem', 'Transplantation of ovary');
insert into posts (title, body) values ('ante vestibulum ante', 'Microscopic examination of specimen from trachea, bronchus, pleura, lung, and other thoracic specimen, and of sputum, culture and sensitivity');
insert into posts (title, body) values ('pretium iaculis diam erat fermentum', 'Control of epistaxis by (transantral) ligation of the maxillary artery');
insert into posts (title, body) values ('quam sapien varius ut blandit', 'Full-mouth x-ray of teeth');
insert into posts (title, body) values ('eros viverra eget congue', 'Replacement and refitting of vaginal diaphragm');
insert into posts (title, body) values ('congue etiam justo etiam', 'Implantation or insertion of biventricular external heart assist system');
insert into posts (title, body) values ('at velit eu est congue', 'Endoscopic retrograde cholangiography [ERC]');
insert into posts (title, body) values ('mauris sit', 'Unilateral injection into breast for augmentation');
insert into posts (title, body) values ('ipsum ac tellus', 'Pharyngeal diverticulectomy');
insert into posts (title, body) values ('magna ac consequat', 'Other excision of vessels, unspecified site');
insert into posts (title, body) values ('elementum pellentesque', 'Arteriography of renal arteries');
insert into posts (title, body) values ('justo sit amet sapien', 'Wedge resection of ovary');
insert into posts (title, body) values ('eu orci mauris lacinia', 'Excision of nipple');
insert into posts (title, body) values ('sapien in sapien iaculis', 'Laparoscopic repair of indirect inguinal hernia with graft or prosthesis');
insert into posts (title, body) values ('augue aliquam erat', 'Other operations on anus');
insert into posts (title, body) values ('nisl ut volutpat sapien', 'Dispensing of other low vision aids');
insert into posts (title, body) values ('ligula vehicula consequat', 'Other glossotomy');
insert into posts (title, body) values ('magnis dis', 'Refusion of lumbar and lumbosacral spine, anterior column, anterior technique');
insert into posts (title, body) values ('luctus ultricies', 'Incision of gum or alveolar bone');
insert into posts (title, body) values ('ultrices posuere cubilia', 'Injection or infusion of biological response modifier [BRM] as an antineoplastic agent');
insert into posts (title, body) values ('vel accumsan tellus nisi', 'Hypothermia (central) (local)');
insert into posts (title, body) values ('interdum venenatis turpis enim blandit', 'Implantation or replacement of automatic cardioverter/defibrillator, total system [AICD]');
insert into posts (title, body) values ('nunc commodo placerat praesent blandit', 'Tendon graft');
insert into posts (title, body) values ('nibh in hac habitasse platea', 'Closure of fistula of mouth');
insert into posts (title, body) values ('morbi vestibulum velit', 'Tendon pulley reconstruction other than hand');
insert into posts (title, body) values ('amet erat nulla tempus vivamus', 'Other tenodesis of hand');
insert into posts (title, body) values ('maecenas pulvinar', 'Open reduction of maxillary fracture');
insert into posts (title, body) values ('vulputate luctus cum sociis', 'Implantation or replacement of carotid sinus stimulation lead(s) only');
insert into posts (title, body) values ('volutpat dui maecenas tristique', 'Other repair of knee');
insert into posts (title, body) values ('dolor sit amet', 'Internal fixation of bone without fracture reduction, carpals and metacarpals');
insert into posts (title, body) values ('id justo', 'Total excision of pineal gland');
